### ISSUE TITLE
Demo needed

### ISSUE THREAD

**Issue by chirag-jn** [SDOS2020/Team_3_Reactonite#124]
Create a demo of the working of Reactonite which we can add in README so that a user can just refer the video/GIF before actually starting using the project.

**Comment by anoushkanarang** [comment]
Please refer to this [link](https://drive.google.com/file/d/1ty_ipntzC1ScgNNYKT7uJO_rnb26lwn6/view?usp=sharing) for the draft of the demo video

**Comment by anoushkanarang** [comment]
GIF for NonGUI Component
![Reactonite_NonGUI](https://user-images.githubusercontent.com/62336310/132125374-4fe86d49-ee49-40a6-ae65-ddae4a90d9a8.gif)
